# Generated by Django 5.2.8 on 2025-12-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(default="🏪", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Main Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="priceentry",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="unit",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="icon",
            field=models.CharField(default="📦", max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(default="kg", max_length=20)),
                ("image", models.ImageField(blank=True, null=True, upload_to="items/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Items",
                "ordering": ["subcategory", "name"],
                "unique_together": {("subcategory", "name")},
            },
        ),
        migrations.AddField(
            model_name="priceentry",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_entries",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="usercategorypermission",
            name="items",
            field=models.ManyToManyField(blank=True, to="core.item"),
        ),
        migrations.AddField(
            model_name="category",
            name="main_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.maincategory",
            ),
        ),
        migrations.RemoveField(
            model_name="priceentry",
            name="subcategory",
        ),
    ]
