# Generated by Django 5.2.8 on 2025-12-04 09:17

from django.db import migrations


def populate_usernames(apps, schema_editor):
    """Populate username from email for existing users"""
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        if not user.username:
            # Extract username from email (part before @)
            if user.email:
                base_username = user.email.split('@')[0]
            else:
                base_username = f"user{user.id}"
            
            # Ensure uniqueness
            username = base_username
            counter = 1
            while User.objects.filter(username=username).exists():
                username = f"{base_username}{counter}"
                counter += 1
            
            user.username = username
            user.save()


def reverse_populate(apps, schema_editor):
    """Reverse: set usernames back to None"""
    User = apps.get_model('core', 'User')
    User.objects.all().update(username=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_username_field"),
    ]

    operations = [
        migrations.RunPython(populate_usernames, reverse_populate),
    ]
