# Generated by Django 6.0 on 2025-12-30 08:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_price_approval_and_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('price_add', 'Price Added'), ('price_update', 'Price Updated'), ('category_view', 'Category Viewed'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('permission_change', 'Permission Changed'), ('rating_add', 'Rating Added'), ('rating_update', 'Rating Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('business_head', 'Business Head'), ('farmer', 'Farmer'), ('buyer', 'Buyer'), ('store_manager', 'Store Manager')], default='buyer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='core.store'),
        ),
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, '0 - Poor'), (5, '5 - Average'), (10, '10 - Excellent')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('rated_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.item')),
                ('store_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to='core.store')),
            ],
            options={
                'verbose_name': 'Item Rating',
                'verbose_name_plural': 'Item Ratings',
                'ordering': ['-rated_date', '-created_at'],
                'unique_together': {('item', 'store', 'rated_date')},
            },
        ),
    ]
