# Generated by Django 6.0 on 2025-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_store_alter_activitylog_action_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('business_head', 'Business Head'), ('farmer', 'Farmer'), ('buyer', 'Buyer'), ('store_manager', 'Store Manager'), ('team_leader', 'Team Leader')], default='buyer', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='itemrating',
            unique_together={('item', 'store', 'store_manager', 'rated_date')},
        ),
    ]
