# Generated by Django 6.0 on 2026-01-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_team_leader_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrating',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ratings/%Y/%m/%d/'),
        ),
    ]
