# Generated by Django 6.0 on 2026-01-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_photo_to_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_stores',
            field=models.ManyToManyField(blank=True, related_name='store_heads', to='core.store'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('business_head', 'Business Head'), ('farmer', 'Farmer'), ('buyer', 'Buyer'), ('store_manager', 'Store Manager'), ('team_leader', 'Team Leader'), ('store_head', 'Store Head')], default='buyer', max_length=20),
        ),
    ]
