# Generated by Django 6.0 on 2026-01-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_store_head_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrating',
            name='rating',
            field=models.IntegerField(choices=[(-1, 'N/A - Not Available'), (0, '0 - Poor'), (5, '5 - Average'), (10, '10 - Excellent')]),
        ),
    ]
